### PR TITLE
Enable the use of the -json flag and update go.mod paths

### PR DESCRIPTION
**Pull request by rstandt**

### CODE REVIEW

**Comment by mukerjee** [comment]
oh lol, this fix is from the coder.com people

**Review by mukerjee — APPROVED** [review]
LGTM, but i don't think you had to update the paths in the `.go` files. i think just updating go.mod would have been enough? 🤔

**Comment by rstandt** [comment]
> LGTM, but i don't think you had to update the paths in the `.go` files. i think just updating go.mod would have been enough? 🤔

I think it had something to do with the packages having the path `internal/*` ? When I tried running CA using the version of this with only go.mod updated it yelled at me about this

**Review by dtnaylor — APPROVED** [review]
LGTM.

I don't know enough about go mod to say much about the paths—I remember we had a similar problem with a prometheus library back when we vendored things, and I think in that case, we solved it by just changing the name of the directory we checked our fork out into from "nefeli" to "prometheus." That's not really an option here with go mod, I guess.

**Pull request merged**
